### ISSUE TITLE
If no data is available excel sheet should be empty

### ISSUE THREAD

**Issue by dlangenk** [biigle/reports#118]
At least for the area report the excel sheet contains the string "No labels found" if no labels are present in a volume. For processing these automatically it would be great if the reports would be either empty or contain just the header (preferred [by me]).

**Comment by mzur** [comment]
I think this is done with all Excel reports. I also think that the report should contain *something* even if no data was found, so the user knows that everything worked. While I still think that the report structure should be kept stable (#119), I don't have as strong an opinion on this one.

**Comment by dlangenk** [comment]
Then let's keep it as is for now (#118 and #119), so there are no breaking changes with external scripts.
