### ISSUE TITLE
Area report contains the volume name in first line

### ISSUE THREAD

**Issue by dlangenk** [biigle/reports#119]
At least the area report contains the volume name in the first row. Usually you would expect to have the headers in the first row. We could set the volume name as the sheet name that would be much more useful I guess.

**Comment by mzur** [comment]
While you have a point:

1. The first line may also contain the user or label tree name if the report is split by user or label tree. In this case, the worksheet name is indeed the volume name. But there will still be cases where the first line contains something else than the column headers.
2. I would only change the report structure if there is an actual bug. Who knows how many people already got used to the current structure and built their own processing pipeline on top of that?

So I'd rather be against the change you propose.

**Comment by dlangenk** [comment]
As indicated in #118 I would keep it as is to not introduce breaking changes in external scripts.
