### ISSUE TITLE
Add width and height attributes to Video annotation report

### ISSUE THREAD

**Issue by ToukL** [biigle/reports#120]
We would like to run a script using the API to extract some useful information from video annotation report but we need the video dimensions (height and width). What do you think about adding an 'attributes' column to this report type, as in image CSV annotation report with those info ?

**Comment by mzur** [comment]
Sounds good :+1: Do you want to implement this?

The new column should be added as the last column so existing workflows/scripts are not broken.

**Comment by ToukL** [comment]
> Sounds good 👍 Do you want to implement this?

Yes I can try. As I understand the Video `attrs` attribute is already filled with dimensions when a new video is processed so if we ask for this attribute in the report it will be good ?

**Comment by mzur** [comment]
Yes!

**Comment by mzur** [comment]
It should be enough if you add the `attrs` column to the [query](https://github.com/biigle/reports/blob/7a19647cc5ed47775adeab2bcd99a7e37b51e746/src/Support/Reports/Volumes/VideoAnnotations/CsvReportGenerator.php#L202) and then to the [CSV](https://github.com/biigle/reports/blob/7a19647cc5ed47775adeab2bcd99a7e37b51e746/src/Support/Reports/Volumes/VideoAnnotations/CsvReportGenerator.php#L261). Then add/update the tests and the manual.
